// Copyright (c) 2026 Sascha G. Eurich, Melowsyne UNIPESSOAL LDA
// SPDX-License-Identifier: MIT
//
// Fountain v2.2 message authentication (HMAC-SHA256) — mirror of the
// normative server side fountain_proto/auth.py, anchored to the golden
// vector (tests/test_auth_golden.py, resp. test/test_auth.cpp here).
// The key must NEVER be logged or quoted in error messages.
#pragma once

#include <array>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

#include <nlohmann/json.hpp>

#include <fountainer/protocol/fountain_messages.hpp>

namespace fountainer::protocol {

// Envelope fields that are NOT part of the canonical body.
inline constexpr std::array<std::string_view, 7> kEnvelopeFields =
    {"v", "type", "serial", "ts", "msg_id", "in_reply_to", "auth"};

// Auth parameters constant per session (nonces come from the handshake).
struct AuthContext {
    std::vector<std::uint8_t> key;    // 32 bytes
    std::string kid;
    std::string device_id;
    std::string server_nonce;         // base64, generated by US
    std::string client_nonce;         // base64, from the device's hello
};

nlohmann::json canonical_body(const nlohmann::json& msg);
std::string body_hash_hex(const nlohmann::json& msg);

// 13 fields, 0x1F-separated, exact order (AUTH-CONTRACT D.1).
std::string mac_input(const nlohmann::json& msg, const AuthContext& ctx,
                      Direction dir, std::string_view kid, std::int64_t seq);

// base64(HMAC-SHA256(key, raw)[0..15])
std::string compute_mac(const std::vector<std::uint8_t>& key,
                        std::string_view raw);

// Sets msg["auth"] = {kid, seq, mac}.
void sign(nlohmann::json& msg, const AuthContext& ctx, std::int64_t seq,
          Direction dir);

struct VerifyResult {
    bool ok;
    std::string reason;   // "ok" | "missing_auth" | "kid_mismatch" |
                          // "bad_seq" | "mac_mismatch"
};

// Checks only integrity/authenticity; anti-replay is the job of AntiReplay.
VerifyResult verify(const nlohmann::json& msg, const AuthContext& ctx,
                    Direction dir);

// Strictly increasing sequence counter per (session, direction); reset =
// new instance per connection.
class AntiReplay {
public:
    bool check(std::int64_t seq)
    {
        if (seq <= last_) {
            return false;
        }
        last_ = seq;
        return true;
    }

    std::int64_t last() const { return last_; }

private:
    std::int64_t last_ = 0;
};

// Reads 64 hex characters (+ optional whitespace) -> 32 bytes. Throws
// std::runtime_error WITHOUT the key contents in the message.
std::vector<std::uint8_t> load_hmac_key_file(const std::string& path);

}  // namespace fountainer::protocol
